### ISSUE TITLE
`BTreeMap<u16, Vec<u8>>` type broken in apply scenario

### ISSUE THREAD

**Issue by da-x** [chinedufn/dipa#4]
Hi,

In the example below quick-check created values that found an issue in applying a delta. This kind of test can be extended to more complex types for arbitrary-generated values.

```
thread 'main' panicked at 'slice index starts at 23 but ends at 3', /home/dan/.cargo/git/checkouts/dipa-eb7bc35c193e0264/cfc0a48852df/src/sequence/sequence_delta_patch_towards.rs:70:31
```

```rust
use dipa::{DiffPatch, Diffable, Patchable};
use quickcheck::quickcheck;
use quickcheck_derive::Arbitrary;
use serde_derive::{Deserialize, Serialize};
use bincode::Options;
use std::collections::BTreeMap;

#[derive(Clone, Eq, PartialEq, PartialOrd, Ord, Debug, DiffPatch, Serialize, Deserialize, Arbitrary)]
pub struct Basic {
    pub items: BTreeMap<u16, Vec<u8>>,
}

fn tester(mut a: Basic, b: Basic) -> bool {
    let bin = bincode::options().with_varint_encoding();
    let created = a.create_delta_towards(&b);

    let serialized = bin.serialize(&created.delta).unwrap();
    let deserialized: <Basic as dipa::Diffable<'_, '_, Basic>>::DeltaOwned =
        bin.deserialize(&serialized).unwrap();

    a.apply_patch(deserialized);
    return a == b;
}

fn main() {
    quickcheck(tester as fn(Basic, Basic) -> bool);
}
```

Example dependencies:

```toml
dipa = { git = "https://github.com/chinedufn/dipa", features = [ "derive"] }
serde_derive = "1"
serde = "1"
quickcheck = "0.8"
quickcheck_macros = "0.8"
quickcheck_derive = "0.3"
rand = "0.6"
bincode = "1.3"
```
